stages:
   get_data:
      cmd: python src/01_get_data.py --config=configs/config.yaml
      deps:
        - src/01_get_data.py
        - src/utils/common_utils.py
        - configs/config.yaml
      outs:
        - data/cat
        - data/dog